encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("wiki/<str:title>/edit", views.entry_edit, name="entry_edit"),
    path("create/", views.create, name="create"),
    path("wiki/", views.random_page, name="random_page"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import random

from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

from . import util

from markdown2 import Markdown


class SearchForm(forms.Form):
    search = forms.CharField(label="Search",
        widget=forms.TextInput(attrs={'placeholder': 'Search'}))

class CreateForm(forms.Form):
    title = forms.CharField(label="Title",
        widget=forms.TextInput(attrs={'placeholder': 'Title'}))

    text = forms.CharField(widget=forms.Textarea(attrs={'placeholder': "Enter the page's content"}))

class EditForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={'placeholder': "Edit the page's content"}))    

def index(request):
    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():
            search_input = form.cleaned_data["search"]

            #check if search input matches to one of the entries 
            if search_input in util.list_entries():
                page = util.get_entry(search_input)
                page_converted = Markdown().convert(page)
                return HttpResponseRedirect(f"wiki/{search_input}")
            
            #generate a list of search matches
            search_matches = [] 
            for entry in util.list_entries():
                if search_input.lower() in entry.lower():
                    search_matches.append(entry)
            
            #check if there are no found pages
            if not search_matches:
                contex = {
                    "error_message" : f"Search: No results for [{search_input}] were found",
                    "form" : SearchForm(),
                }
                return render(request, "encyclopedia/error.html", contex)

            #render the page displaying the search results    
            return render(request, "encyclopedia/search.html", {
                "entries" : search_matches,
                "form" : SearchForm(),
            })

    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "form" : SearchForm(),
    })


def entry(request, title):
    if title in util.list_entries():
        page = util.get_entry(title)
        page_converted = Markdown().convert(page)
        contex = {
            "title" : title,
            "page" : page_converted,
            "form" : SearchForm(),
        }
        return render(request, "encyclopedia/entry.html", contex)

    else:
        contex = {
            "error_message" : f"Error: Requested page [{title}] is not found",
            "form" : SearchForm(),
        }
        return render(request, "encyclopedia/error.html", contex)

def create(request):
    
    if request.method == "POST":
        form = CreateForm(request.POST)
        if form.is_valid():
            form_title = form.cleaned_data["title"]
            form_text = form.cleaned_data["text"]

            #check if encyclopedia entry already exists 
            if form_title in util.list_entries():
                contex = {
                    "error_message" : f"Error: Page with title [{form_title}] already exists",
                    "form" : SearchForm(),
                }
                return render(request, "encyclopedia/error.html", contex)

            util.save_entry(form_title, form_text)
            return HttpResponseRedirect(reverse("encyclopedia:index") + f"wiki/{form_title}")


    return render(request, "encyclopedia/create.html", {
        "entries": util.list_entries(),
        "form" : SearchForm(),
        "CreateForm" : CreateForm(),
    })

def random_page(request):
    random_page = random.choice(util.list_entries())
    return HttpResponseRedirect(reverse("encyclopedia:index") + f"wiki/{random_page}")


def entry_edit(request, title):
    if request.method == "GET":
        page = util.get_entry(title)
        contex = {
            "title" : title,
            "form" : EditForm(initial={'text': page}),
        }
        return render(request, "encyclopedia/entry_edit.html", contex)

    if request.method == "POST":
        form = EditForm(request.POST)
        if form.is_valid():
            form_text = form.cleaned_data["text"]
            util.save_entry(title, form_text)
            return HttpResponseRedirect(reverse("encyclopedia:index") + f"wiki/{title}")

encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}
    <h2>Create New Page</h2>
    <form action="{% url 'encyclopedia:create' %}" method="post">
        {% csrf_token %}
        <h5>{{ CreateForm.title }}</h5>
        <h5 class="create-text-area">{{ CreateForm.text }}</h5>
        <button type="submit" class="btn btn-light">Submit</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    {{ page | safe }}
    <a href=/wiki/{{title}}/edit>Edit This Page</a>
{% endblock %}

encyclopedia/templates/encyclopedia/entry_edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Editing {{ title }}
{% endblock %}

{% block body %}
    <h2>Edit page {{ title }} </h2>
    <form method="post">
        {% csrf_token %}
        <h5>{{ form.text }}</h5>
        <button type="submit" class="btn btn-light">Submit</button>
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1> {{ error_message }}</h1>

{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li class="entry-li"><a href=wiki/{{entry}}>{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:index' %}" method="post">
                    {% csrf_token %}
                    {{ form.search }}
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Wiki Search
{% endblock %}

{% block body %}
    <h1>Found pages:</h1>

    <ul>
        {% for entry in entries %}
            <li class="entry-li"><a href=wiki/{{entry}}>{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}